# https://playwright.dev/docs/docker
FROM mcr.microsoft.com/playwright:v1.46.0-noble

ARG USERNAME=playwright
ARG USER_UID=100001
ARG USER_GID=${USER_UID}

# Create the user and make sure also in the root user group
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -G root -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME \
    && mkdir -p /workspace \
    && chown -R ${USER_UID}:${USER_GID} /workspace
