# Generated by Django 5.1 on 2024-08-27 20:05

import django.core.validators
import orgtorii.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_newslettersignup_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerReviewMVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_domain', models.CharField(blank=True, max_length=255, validators=[django.core.validators.DomainNameValidator()])),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('estimated_review_date', models.DateField(validators=[orgtorii.core.models.validate_not_in_future])),
                ('tenure_months', models.PositiveSmallIntegerField()),
                ('current_employee', models.BooleanField(default=False)),
                ('payslip', models.FileField(blank=True, upload_to=orgtorii.core.models.get_payslip_upload_path)),
                ('review_title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)])),
                ('review', models.TextField(validators=[django.core.validators.MinLengthValidator(160)])),
                ('culture_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('work_life_balance_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('leadership_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('opportunities_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('compensation_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('base_annual_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('additional_annual_compensation', models.PositiveIntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
